### ISSUE TITLE
Formatting on "Getting Support"

### ISSUE THREAD

**Issue by ELKER54** [Horizon-Hosting/Documentation#28]
On the [documentation](https://github.com/Horizon-Hosting/Documentation/blob/pre-release/knowledgebase/getting_support.md)
Where it says \`#new-ticket' it should be `#new-ticket`.
This is it compared to the community support channel reference:
https://s.elker54.com/RIZo8/HUrOKIfA88.png/raw

**Comment by Mack29446** [comment]
Fixed in #30
